### ISSUE TITLE
Failing unit tests (intermittent)

### ISSUE THREAD

**Issue by michaeltelford** [michaeltelford/wgit#18]
## Description

Failing test below (AND ANOTHER IN THE COMMENTS):

```bash
$ bundle exec toys test
Run options: --seed 57303

# Running:

.............................................................................E.................................................................................................................................................................................................................................................

Finished in 14.287830s, 22.3267 runs/s, 152.9274 assertions/s.

  1) Error:
TestBase#test_quotes_crawler:
NoMethodError: undefined method `zip' for nil:NilClass
    test/test_base.rb:15:in `parse'
    lib/wgit/base.rb:24:in `block in run'
    lib/wgit/crawler.rb:200:in `crawl_url'
    lib/wgit/crawler.rb:118:in `crawl_site'
    lib/wgit/dsl.rb:143:in `block in crawl_site'
    lib/wgit/dsl.rb:142:in `each'
    lib/wgit/dsl.rb:142:in `reduce'
    lib/wgit/dsl.rb:142:in `crawl_site'
    lib/wgit/base.rb:24:in `run'
    test/test_base.rb:67:in `test_quotes_crawler'

319 runs, 2185 assertions, 0 failures, 1 errors, 0 skips

Focus on failing tests:
mtest test/test_base.rb:65
[2023-10-06 13:20:11 ERROR]  Minitest failed!
```

## Reproduce

1. Run `bundle exec toys test` a few times and it will eventually show up (probably 1 in 5 test runs).

## Expected Behavior

The test passes every time. All tests passing every time.

## Possible Solutions

1. There could be an issue/bug in the Wgit code which'll need fixed.
2. Or there could be an issue with the test/README example, which'll need updated in both places (tests and README) if changed.

## Tests

What tests would prove this bug is fixed?

1. `TestBase#test_quotes_crawler`

**Comment by michaeltelford** [comment]
Another intermittent failing unit test is this one, doesn't appear connected to the test above:

```sh
$ bundle exec toys test
Run options: --seed 29550

# Running:

...............................F..................................................................................................................................................................................................................................................................................................................................

Finished in 14.205508s, 24.9199 runs/s, 169.8637 assertions/s.

  1) Failure:
TestDatabase#test_bulk_upsert__docs [test/test_database.rb:225]:
Expected: 3
  Actual: 4

354 runs, 2413 assertions, 1 failures, 0 errors, 0 skips

Focus on failing tests:
mtest test/test_database.rb:208
[2023-11-10 13:06:31 ERROR]  Minitest failed!
```
Also needs fixed along with the above test failure.

**Comment by michaeltelford** [comment]
The most intermittent test failures I've seen in one test run is:

```
  1) Failure:
TestIndexer#test_index_url__upsert [test/test_indexer.rb:529]:
Expected: 1
  Actual: 0

  2) Failure:
TestDSL#test_search [test/test_dsl.rb:386]:
Expected: 1
  Actual: 0

  3) Failure:
TestDocumentExtractors#test_document_extractor__init_from_database [test/test_document_extractors.rb:474]:
Expected: 1
  Actual: 0

  4) Failure:
TestReadme#test_quotes__dsl_index [test/test_readme.rb:69]:
Expected: 1
  Actual: 0

403 runs, 2696 assertions, 4 failures, 0 errors, 0 skips
```

Re-running the tests saw the above pass meaning they're all intermittent failures, possibly due to a single issue. But maybe not. Needs investigating.

**Comment by michaeltelford** [comment]
It's worth nothing that the tests also fail intermittently in the GH actions CI build. This issue should address those also.
